# Generated by Django 5.1.1 on 2024-10-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('business_type', models.CharField(choices=[('Hospital', 'Hospital'), ('Saloon', 'Saloon'), ('Restaurant', 'Restaurant')], max_length=50)),
                ('business_mail', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=254)),
            ],
        ),
    ]
