# Generated by Django 5.1.1 on 2024-10-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessioncrud', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_id',
            field=models.PositiveIntegerField(default=333, unique=True),
            preserve_default=False,
        ),
    ]
