# Generated by Django 5.1.1 on 2024-10-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessioncrud', '0003_business_business_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_id',
            field=models.PositiveIntegerField(),
        ),
    ]
