# Generated by Django 5.1.1 on 2024-10-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessioncrud', '0004_alter_business_business_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
