# Generated by Django 5.1.1 on 2024-10-03 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessioncrud', '0005_alter_business_business_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('timeslot', models.CharField(max_length=100)),
                ('session_status', models.CharField(choices=[('isAvailable', 'isAvailable'), ('isBooked', 'isBooked'), ('isCancelled', 'isCancelled'), ('isCompleted', 'isCompleted')], default='isAvailable', max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessioncrud.business')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessioncrud.customer')),
            ],
        ),
    ]
