# Generated by Django 5.1.1 on 2024-10-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessioncrud', '0006_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_id',
            field=models.PositiveIntegerField(default=444, unique=True),
            preserve_default=False,
        ),
    ]
